### ISSUE TITLE
Configurable RADIUS accounting sync interval

### ISSUE THREAD

**Issue by robcza** [whalebone/KresMan#5]
Configure through env the interval of how frequently (in seconds) will kresman push the radius information to the resolver processes.
This sync should be independent from the domain sync, domains should not be processed during this step.

**Comment by Elctro** [comment]
Threse is a values `kres_update_interval` which means a one cycle of update. How frequently (default) kresman shall update what exactly? E.g. 4 of 5 cycles update identity only, 1 or 5 updates all.
